#!/bin/csh -f

set DIR=`pwd`
echo
echo $DIR

#link to openmpi
#setenv LD_LIBRARY_PATH /usr/local/pkg/openmpi/lib

#directory of excutable
#set DIR = /nfs/user02/linli/FronTier_devel/subsurf

#mpirun path
set MPIRUN = /usr/local/pkg/openmpi/bin/mpirun

#run options
echo input file $DIR/in-$1
echo output directory $DIR/out-$1
$MPIRUN -np 1 $DIR/subsurf -d 2 -p 1 1 -i $DIR/in-$1 -o $DIR/out-$1
