#!/bin/csh -f

set DIR = `pwd`
echo
echo $DIR

#link to openmpi
setenv LD_LIBRARY_PATH /usr/local/pkg/openmpi/lib

#directory of excutable

#mpirun path
set MPIRUN = /usr/local/pkg/openmpi/bin/mpirun

#run options
echo input file $DIR/in-$1
echo output directory $DIR/out-$1
$MPIRUN -np 1 $DIR/finance -d 1 -p 1 -i $DIR/in-$1 -o $DIR/out-$1
